### ISSUE TITLE
Outputfile(.phy) couldn't be open by Phylip and FastTree 

### ISSUE THREAD

**Issue by liurongbio** [edgardomortiz/vcf2phylip#25]
Hi, Edgardo

I tried to use vcf2phylip.py to preprare the inputfile for phylip as well as FastTree, and encountered the following problems. Would you please to help me out? Thank you very much.

python ../vcf2phylip/vcf2phylip.py -i ../chr251.LDfilter.vcf -r

phylip-3.697 dnadist "ERROR: Unexpected end-of-file."

FastTree Version 2.1.10 "No sequence in phylip line"

Best,

Rong Liu

**Comment by edgardomortiz** [comment]
Hello Rong Liu,

I need more info, does `vcf2phylip` produce any error? if not, what type of output does it produce? if everything looks normal to you, would you mind sharing the vcf (if it is too big, a few thousand lines will suffice).

Edgardo

**Comment by liurongbio** [comment]
Thank you for your consideration.  
Well, vcf2phylip produced no error. Please see the attachments including subsets of inputfile (.vcf) and outputfile (.phy) . 
I guess that the problem maybe the format of the outputfile (.phy) (Each line shows a single sample genotype without interval). But I don't know how to solve it.
Rong Liu
[Attachments.zip](https://github.com/edgardomortiz/vcf2phylip/files/4783993/Attachments.zip)

**Comment by edgardomortiz** [comment]
I didn't understand what you meant by: "Each line shows a single sample genotype without interval", please clarify, perhaps you are expecting a different format?

However, I looked at your attachments:

head2000.vcf is correctly formatted and produces a correct matrix by using `vcf2phylip.py -i head2000.vcf` or `vcf2phylip.py -i head2000.vcf -r` in my system with python 2 or python 3.

tail2000.vcf (which I guess you cut using `tail` from bash) lacks the VCF header and therefore is improperly formatted (it doesn't have the line that starts with `#CHROM ...` where the sample names come from). In this case `vcf2phylip` produces a matrix without phylip header or sample names. I will fix my script so if the header is not found in the VCF, no matrix is produced.

Finally, I concatenated head10.phy and tail10.phy, and I modified the header to `19 2175716`, because it only contains 19 samples, and the matrix loads correctly. So I don't see a problem with your cut matrix.

Take a look at the matrix I get by using `vcf2phylip.py -i head2000.vcf`:
[head2000.min4.phy.zip](https://github.com/edgardomortiz/vcf2phylip/files/4784917/head2000.min4.phy.zip)

Perhaps your phylip or fasttree commands are missing something? what were they?
